### ISSUE TITLE
This isn't even funny

### ISSUE THREAD

**Issue by ghost** [PennartLoettring/Poettrix#1]
Not even a little

**Comment by ghost** [comment]
sPREAD THE WORD LITTLE bIRD!

also, HAPPY INTERNATIONAL CAPSLOCK DAY!

**Comment by PennartLoettring** [comment]
oh you lennert
![pennart_loettring](https://cloud.githubusercontent.com/assets/9341231/4742861/7c5bcbe0-5a22-11e4-8d07-f60a5f0c908d.png)
